return {
    require('plugins.colorizer'),
    require('plugins.gitsigns'),
    require('plugins.which-key'),
    require('plugins.telescope'),
    require('plugins.lazydev'),
    require('plugins.nvim-lspconfig'),
    require('plugins.conform'),
    require('plugins.blink'),
    require('plugins.everforest'),
    require('plugins.todo-comments'),
    require('plugins.mini'),
    require('plugins.treesitter'),
    --    require('plugins.copilot'),
    require('plugins.indent-blankline'),
    require('plugins.render-markdown'),
}
